name: build podman
on: 
  push:
    tags:
      - build*
jobs:
  build-podman:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: [ centos7 ]
    steps:
      - name: Run actions/checkout for this repo
        uses: actions/checkout@v2
        with:
          path: checkout_build_podman
          persist-credentials: false
      - name: read config JSON file
        id: read-config
        run: |
          json="$(cat checkout_build_podman/config/${{ matrix.config }}.json)"
          json="${json//'%'/'%25'}"
          json="${json//$'\r'/'%0D'}"
          json="${json//$'\n'/'%0A'}"
          echo ::set-output "name=config::$json"
      - name: Run actions/setup-go with go-version ${{ fromJson(steps.read-config.outputs.config).go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ fromJson(steps.read-config.outputs.config).go-version }}
      - name: mkdir
        run: |
          mkdir $GITHUB_WORKSPACE/output
          mkdir -p $GITHUB_WORKSPACE/gopath/src/github.com/containers
      - name: Run actions/checkout for containers/conmon
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJson(steps.read-config.outputs.config).gitrepos.conmon.repository }}
          ref: ${{ fromJson(steps.read-config.outputs.config).gitrepos.conmon.ref }}
          path: gopath/src/github.com/containers/conmon
          persist-credentials: false
      - name: Run actions/checkout for containers/podman
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJson(steps.read-config.outputs.config).gitrepos.podman.repository }}
          ref: ${{ fromJson(steps.read-config.outputs.config).gitrepos.podman.ref }}
          path: gopath/src/github.com/containers/podman
          persist-credentials: false
      - name: Run actions/checkout for CNI/plugins
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJson(steps.read-config.outputs.config).gitrepos.CNI-plugins.repository }}
          ref: ${{ fromJson(steps.read-config.outputs.config).gitrepos.CNI-plugins.ref }}
          path: gopath/src/github.com/containernetworking/plugins
          persist-credentials: false
      - name: check podman version
        run: |
          podman --version
      - name: podman build
        run: |
          bash checkout_build_podman/build_container.bash ${{ matrix.config }}
      - name: podman run
        run: |
          podman run --rm -v $GITHUB_WORKSPACE/output:${{ matrix.installprefix }} -v $GITHUB_WORKSPACE/checkout_build_podman:/checkout_build_podman -v /opt/hostedtoolcache/go:/opt/hostedtoolcache/go -v $GITHUB_WORKSPACE/gopath:/gopath -e GOROOT=/opt/hostedtoolcache/go/${{ matrix.go-version }}/x64 -e PATH=/opt/hostedtoolcache/go/${{ matrix.go-version }}/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin localhost/build-podman:${{ matrix.config }} bash /checkout_build_podman/container_build_command.sh ${{ matrix.installprefix }}
      - name: check output
        run: |
          ls $GITHUB_WORKSPACE/output
      - name: download extra executables
        run: |
          curl -o output/bin/crun -L -s https://github.com/containers/crun/releases/download/${{ matrix.download.crun }}/crun-${{ matrix.download.crun }}-linux-amd64
          chmod 755 output/bin/crun
          curl -o output/bin/slirp4netns -L -s https://github.com/rootless-containers/slirp4netns/releases/download/${{ matrix.download.slirp4netns }}/slirp4netns-x86_64
          chmod 755 output/bin/slirp4netns
          curl -o output/bin/fuse-overlayfs -L -s https://github.com/containers/fuse-overlayfs/releases/download/${{ matrix.download.fuse-overlayfs }}/fuse-overlayfs-x86_64
          chmod 755 output/bin/fuse-overlayfs
      - name: set name
        id: setname
        run: echo ::set-output name=outputname::build-podman_${{ github.sha }}__${{ matrix.centos-version }}__${{ matrix.podman-version }}__${{ matrix.conmon-version }}__${{ matrix.CNI-plugins-version }}__${{ matrix.go-version }}__${{ matrix.crun-version }}__${{ matrix.slirp4netns-version }}__${{ matrix.fuse-overlayfs-version }}
      - name: create tar archive
        run: |
          mv output ${{steps.setname.outputs.outputname}}
          tar --force-local -cvf ${{steps.setname.outputs.outputname}}.tar ${{steps.setname.outputs.outputname}}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{steps.setname.outputs.outputname}}.tar
          path: ${{steps.setname.outputs.outputname}}.tar
